server:
  port: 2003

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: Satya@1009
    url: jdbc:postgresql://casalocal.com:5432/usermsdev
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      mode: always
